ALTER TABLE deadlines ADD COLUMN IF NOT EXISTS warning_id TEXT NOT NULL DEFAULT '';
ALTER TABLE deadlines ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
ALTER TABLE deadlines ADD COLUMN IF NOT EXISTS is_completed BOOLEAN NOT NULL DEFAULT FALSE;
