const KNOWN_ROUTE_PREFIXES = new Set([
  "landing",
  "home",
  "auth",
  "login",
  "register",
  "signup",
  "reset-password",
  "pricing",
  "verify-email",
  "invite",
  "checklist",
  "start",
  "guides",
  "probate-process",
  "probate-timeline",
  "executor-checklist",
  "small-estate-affidavit",
  "probate-texas",
  "what-to-do-when-someone-dies",
  "probate-california",
  "probate-florida",
  "transfer-car-title-after-death",
  "life-insurance-claim-process",
  "intestate-without-will",
  "probate-cost",
  "estate-settlement-checklist",
  "estate-path-guide",
  "competitor-comparison",
  "terms",
  "privacy",
  "onboarding",
  "firm",
  "reports",
  "dashboard",
  "assets",
  "asset",
  "add-asset",
  "add-liability",
  "upload",
  "documents",
  "inbox",
  "follow-ups",
  "roadmap",
  "roadmap-old",
  "settlement-trail",
  "forms",
  "probate",
  "discovery",
  "liabilities",
  "heirs",
  "accounting",
  "tax-management",
  "receipts",
  "distribution",
  "non-probate",
  "profile",
  "settings",
  "help",
  "estate-agent",
  "estates",
  "marketplace-legacy",
  "advisor",
  "marketplace",
  "my-bookings",
  "consultations",
  "payment-success",
  "admin",
  "debug",
]);

export function isKnownSpaPath(pathname: string): boolean {
  const normalizedPath = pathname.replace(/\/+$/, "") || "/";
  if (normalizedPath === "/") {
    return true;
  }

  const [firstSegment] = normalizedPath.split("/").filter(Boolean);
  return KNOWN_ROUTE_PREFIXES.has(firstSegment);
}
