import { motion } from "framer-motion";
import { Download, Map, FileCheck, Calculator } from "lucide-react";

const samples = [
    {
        icon: Map,
        title: "Sample Executor Roadmap",
        description: "A real California probate roadmap — every phase, task, deadline, and court requirement, exactly as the app generates it.",
        file: "/samples/sample-executor-roadmap.pdf",
        tag: "12 pages · California"
    },
    {
        icon: FileCheck,
        title: "Sample Auto-Filled Court Form",
        description: "See how a Petition for Probate comes out — populated from estate data, ready for review and filing.",
        file: "/samples/sample-court-form.pdf",
        tag: "Form excerpt · Redacted"
    },
    {
        icon: Calculator,
        title: "Sample Final Accounting",
        description: "The fiduciary accounting report you'd hand to the court and beneficiaries — receipts, disbursements, and balances.",
        file: "/samples/sample-final-accounting.pdf",
        tag: "Full report · Redacted"
    }
];

export function TestimonialsSection() {
    return (
        <section className="py-24 bg-gray-50/50 border-y border-border/30">
            <div className="section-container">
                <div className="text-center mb-16">
                    <motion.h3
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        className="text-primary font-bold tracking-[0.2em] uppercase text-sm mb-6"
                    >
                        Proof, Not Promises
                    </motion.h3>
                    <motion.h2
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ delay: 0.1 }}
                        className="text-4xl md:text-5xl font-black text-foreground mb-6"
                    >
                        Don't take our word for it. <br className="hidden md:block" />
                        Look at the actual output.
                    </motion.h2>
                    <motion.p
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ delay: 0.2 }}
                        className="text-lg text-muted-foreground font-medium max-w-2xl mx-auto"
                    >
                        Before you trust anyone with your loved one's estate, see exactly what
                        ExpectedEstate produces. These are real documents generated by the platform
                        (identifying details fictionalized).
                    </motion.p>
                </div>

                <div className="grid md:grid-cols-3 gap-8 max-w-6xl mx-auto">
                    {samples.map((s, i) => (
                        <motion.a
                            key={s.title}
                            href={s.file}
                            target="_blank"
                            rel="noopener noreferrer"
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: i * 0.1 }}
                            className="bg-white p-8 rounded-[2rem] shadow-sm border border-border/50 flex flex-col relative group hover:border-primary/40 transition-all hover:shadow-xl"
                        >
                            <div className="p-4 bg-primary/10 rounded-2xl w-fit mb-6 group-hover:bg-primary/15 transition-colors">
                                <s.icon className="w-7 h-7 text-primary" />
                            </div>
                            <span className="inline-block w-fit py-1 px-3 rounded-full bg-slate-100 text-slate-600 text-[10px] font-black uppercase tracking-widest mb-4 border border-slate-200">
                                {s.tag}
                            </span>
                            <h4 className="font-black text-foreground text-xl mb-3">{s.title}</h4>
                            <p className="text-sm text-muted-foreground font-medium leading-relaxed flex-1">
                                {s.description}
                            </p>
                            <div className="mt-6 flex items-center gap-2 text-primary font-bold text-sm group-hover:gap-3 transition-all">
                                <Download className="w-4 h-4" /> View sample PDF
                            </div>
                        </motion.a>
                    ))}
                </div>

                <p className="text-center text-xs text-muted-foreground mt-12 font-medium">
                    ExpectedEstate is self-help software, not a law firm. Samples are illustrative
                    and do not constitute legal advice.
                </p>
            </div>
        </section>
    );
}
